# Generated by Django 4.1.3 on 2022-11-05 14:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulations',
            fields=[
                ('Code', models.IntegerField(max_length=20, unique=True)),
                ('Total_Formation_Weight', models.IntegerField(max_length=200)),
                ('Line_type', models.CharField(choices=[('Raw', 'Raw'), ('Stage', 'Stage'), ('Instr', 'Instr')], max_length=200)),
                ('Ingredient', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=200)),
                ('Quantity', models.CharField(max_length=200)),
                ('percentage_weight', models.CharField(max_length=200)),
                ('unit_cost', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Name', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('step', models.CharField(max_length=200)),
                ('instructions', models.CharField(max_length=200)),
                ('special_notes', models.CharField(max_length=200)),
                ('formulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='formulator.formulations')),
            ],
        ),
        migrations.AddField(
            model_name='formulations',
            name='instructions_id',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='formulator.instructions'),
        ),
    ]
