# Generated by Django 4.1.3 on 2022-11-05 14:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('formulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulation',
            fields=[
                ('Code', models.IntegerField(max_length=20, unique=True)),
                ('Total_Formation_Weight', models.IntegerField(max_length=200)),
                ('Line_type', models.CharField(choices=[('Raw', 'Raw'), ('Stage', 'Stage'), ('Instr', 'Instr')], max_length=200)),
                ('Quantity', models.CharField(max_length=200)),
                ('percentage_weight', models.CharField(max_length=200)),
                ('unit_cost', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('Name', models.CharField(max_length=200)),
                ('Purpose', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Formulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='formulator.formulation')),
            ],
        ),
        migrations.RemoveField(
            model_name='instructions',
            name='formulation',
        ),
        migrations.AddField(
            model_name='instructions',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Formulations',
        ),
        migrations.AddField(
            model_name='formulation',
            name='Ingredients',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='formulator.ingredients'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='instructions_id',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='formulator.instructions'),
        ),
        migrations.AddField(
            model_name='instructions',
            name='formulation_field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulator.formulation'),
        ),
    ]
