# Generated by Django 4.1.3 on 2022-11-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulator', '0003_ingredients_code_alter_ingredients_formulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='Code',
            field=models.IntegerField(blank=True, max_length=20, unique=True),
        ),
    ]
