# Generated by Django 4.1.3 on 2022-11-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulator', '0006_alter_instructions_formulation_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='Instructions',
            new_name='Instruction',
        ),
        migrations.RenameField(
            model_name='formulation',
            old_name='instructions_id',
            new_name='instruction_id',
        ),
    ]
