# Generated by Django 4.1.3 on 2022-11-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulator', '0007_rename_ingredients_ingredient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='Formulation',
            new_name='Formulation_id',
        ),
    ]
