# Generated by Django 4.1.3 on 2022-11-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulator', '0008_rename_formulation_ingredient_formulation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='Formulation_id',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='Formulation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulator.formulation'),
        ),
    ]
