# Generated by Django 4.1.3 on 2022-11-05 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulator', '0009_remove_ingredient_formulation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulation',
            name='Ingredients',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='formulator.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='Formulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulator.formulation'),
        ),
    ]
