# Generated by Django 4.1.3 on 2022-11-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulator', '0010_alter_formulation_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulation',
            name='Ingredients',
        ),
        migrations.AddField(
            model_name='formulation',
            name='Ingredients',
            field=models.ManyToManyField(blank=True, to='formulator.ingredient'),
        ),
    ]
