# Generated by Django 4.1.3 on 2022-11-06 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulator', '0011_remove_formulation_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='Formulation',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='step',
        ),
        migrations.AddField(
            model_name='product',
            name='Formulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formulator.formulation'),
        ),
    ]
