# Generated by Django 4.1.3 on 2022-11-06 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulator', '0013_alter_formulation_instruction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Formulation',
        ),
        migrations.AddField(
            model_name='formulation',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulator.product'),
        ),
    ]
