# Generated by Django 4.1.3 on 2022-11-06 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulator', '0014_remove_product_formulation_formulation_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Formulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formulator.formulation'),
        ),
    ]
