# Generated by Django 4.1.3 on 2022-11-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulator', '0016_rename_ingredient_raw_materials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulation',
            old_name='Ingredients',
            new_name='Raw_Materials',
        ),
    ]
