# Generated by Django 4.1.3 on 2022-11-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulator', '0017_rename_ingredients_formulation_raw_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw_materials',
            name='Code',
            field=models.IntegerField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
